theme = "adwaita-dark"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
true-color = true
rulers = [80]
cursorline = true
color-modes = true
insert-final-newline = true
text-width = 72

[editor.file-picker]
hidden = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
G = "goto_file_end"
X = "extend_line_above"
ret = ["move_line_down", "goto_line_start"]
C-n = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-p = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_after"]

[keys.normal.space]
q = ":quit"
n = ":bn"
p = ":bp"
x = { "f" = "file_picker_in_current_buffer_directory", "r" = ":reflow", "u" = ":reload" }

[editor.whitespace.render]
space = "all"
tab = "all"
